### ISSUE TITLE
Minified Dep Bundles are Broken

### ISSUE THREAD

**Issue by Sinjhin** [stealjs/steal-tools#947]
When building the CanJS site if I use `"deps-bundle": "steal-tools bundle --deps"` in my scripts and try to load a demo with that deps-bundle like:
```
<script id="demo-source" main="@empty" src="../../node_modules/steal/steal.js" deps-bundle>
```
It will break on load with the error:
```
steal.js:7390 Error: Error loading "dev-bundle" at http://localhost:8080/dev-bundle.js
TypeError: define is not a function
	    at Object.eval (http://localhost:8080/dev-bundle.js:4:125077)
	    at eval (http://localhost:8080/dev-bundle.js:5:4)
	    at eval (http://localhost:8080/dev-bundle.js:5:98)
	Evaluating http://localhost:8080/dev-bundle.js
```

If I add the `--no-minify` option `"deps-bundle": "steal-tools bundle --deps --no-minify"` it works fine but the deps-bundle is not minified.

**Comment by matthewp** [comment]
Can you recreate with an example app?

**Comment by m-mujica** [comment]
This is a known issue, and it's the reason why we made minify false the default https://github.com/stealjs/steal-tools/pull/905 

To fix it, [this regex](https://github.com/stealjs/steal/issues/1227#issuecomment-318413723) needs to ignore any glob patterns introduced by this node https://github.com/stealjs/steal-tools/blob/master/lib/bundle/add_npm_packages_node.js

**Comment by Sinjhin** [comment]
@m-mujica It looks like the minify false by default is not working in v1.11.3 unless I specifically add the `--no-minify` tag to the script.

**Comment by matthewp** [comment]
@m-mujica is there another existing issue for this?

**Comment by kylegifford** [comment]
I'd like to bump this issue. We have several clients using this, and it would be nice to have the additional speed improvements. Here is an example from Lowe's:

![screenshot 2018-05-25 16 51 09](https://user-images.githubusercontent.com/4341379/40569109-314b7424-603c-11e8-9aac-42e0d661d832.png)
![screenshot 2018-05-25 16 51 25](https://user-images.githubusercontent.com/4341379/40569113-369508d2-603c-11e8-8cf6-fc794ce461d9.png)

**Comment by justinbmeyer** [comment]
@kylegifford is it gzipped?  gzipping often improves payload size even more than minification.  Also, it looks like load is only effected about 60ms.  While that's something, from the slack convo, it looks like you are looking for more substantive improvements?

**Comment by justinbmeyer** [comment]
instead of using a regexp ... I wonder if can-parse could perform well enough here, and be fast enough.  We don't need to support JS's full syntax, only it seems strings and comments?

**Comment by m-mujica** [comment]
Just added a branch with a breaking test, might try to fix it this weekend... anyway, if anyone else picks it there you have the test. 

https://github.com/stealjs/steal-tools/pull/1003
